services:

    payload:
        build: ./payload
        working_dir: /app
        restart: always
        env_file: ".env"
        environment:
            DATABASE_URI: "mongodb://mongo:27017/payload"
        volumes:
            - ./payload:/app
            - /app/node_modules
            - /etc/localtime:/etc/localtime
        depends_on:
            - mongo

    mongo:
        image: mongo:latest
        restart: always
        volumes:
            - db_data:/data/db

    web:
        build: ./web
        restart: always
        depends_on:
            - payload
        volumes:
            - ./web:/home/node/app
            - /etc/localtime:/etc/localtime
        env_file: ".env"
        environment:
            DATABASE_URI: "mongodb://mongo:27017/payload"

    nginx:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./.config/nginx/templates:/etc/nginx/templates
        depends_on:
            - payload
            - web
        env_file: ".env"

volumes:
    db_data:
